In [1]:
import numpy as np

In [2]:
# Lists
# numpy arrays

In [3]:
a_list = [0,1,2,3,4,5]
a_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(a_list)

list

In [5]:
# lists can be nested

In [6]:
complex_list = [
    3,
    [3,4,5],
    [10,20,30],
    ['cat','dog','sog'],
    1
]

In [7]:
complex_list

[3, [3, 4, 5], [10, 20, 30], ['cat', 'dog', 'sog'], 1]

In [8]:
a_list = [0,1,2,3,4,5]
b_list = ['0','1','2','3','4','5']

print(a_list*3)
print(b_list*4)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
['0', '1', '2', '3', '4', '5', '0', '1', '2', '3', '4', '5', '0', '1', '2', '3', '4', '5', '0', '1', '2', '3', '4', '5']


In [9]:
# now let's convert to a numpy array

a_list_np = np.array(a_list)
print(type(a_list))
print(type(a_list_np))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
print(a_list)
print(a_list_np)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [12]:
print(a_list*3)
print(a_list_np*3)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  3  6  9 12 15]


In [13]:
print(a_list_np + 66)

[66 67 68 69 70 71]


In [20]:
for idx, el in enumerate(complex_list):
    el_type = str(type(el)).replace("<class \'", "").replace("\'>","")
    print(f'List element {idx} is {el} and is of type {el_type}.')

List element 0 is 3 and is of type int.
List element 1 is [3, 4, 5] and is of type list.
List element 2 is [10, 20, 30] and is of type list.
List element 3 is ['cat', 'dog', 'sog'] and is of type list.
List element 4 is 1 and is of type int.
